name: Python Package Build & Release

permissions:
  contents: write  # Allow pushing tags and creating releases

on:
  push:
    branches:
      - main  # Runs the build process on every commit to main

  workflow_dispatch:  # Manual trigger for tagging & release
    inputs:
      version_type:
        description: "Version type (major, minor, patch)"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner for .exe creation
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tk pyinstaller pillow
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Generate Executable with PyInstaller
        run: |
          pyinstaller --onedir --windowed --noupx --icon=icon.png --add-data "icon.png;." app.py --name VideoCompressorForDiscord

      - name: Upload ZIP as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VideoCompressorForDiscord
          path: dist/VideoCompressorForDiscord

  release:
    if: github.event_name == 'workflow_dispatch'  # Runs only when manually triggered
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        id: get-latest-tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Determine New Version
        id: new-version
        run: |
          OLD_TAG=${{ env.TAG }}
          VERSION=$(echo $OLD_TAG | sed 's/v//')
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)

          if [ "${{ github.event.inputs.version_type }}" == "major" ]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [ "${{ github.event.inputs.version_type }}" == "minor" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi

          NEW_TAG="v$MAJOR.$MINOR.$PATCH"

          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "Determined new version: $NEW_TAG"

      - name: Download Built Artifact
        uses: actions/download-artifact@v4
        with:
          name: VideoCompressorForDiscord
          path: build_artifact  # Store in a separate folder

      - name: List downloaded files
        run: ls -la build_artifact

      - name: Repackage files into a versioned ZIP
        run: |
          cd build_artifact
          zip -r ../VideoCompressorForDiscord-${{ env.NEW_TAG }}.zip .
          cd ..

      - name: Verify final ZIP
        run: ls -la VideoCompressorForDiscord-${{ env.NEW_TAG }}.zip

      - name: Create and Push New Tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: Release ${{ env.NEW_TAG }}
          body: "New release: ${{ env.NEW_TAG }}"
          draft: false
          prerelease: false
          files: VideoCompressorForDiscord-${{ env.NEW_TAG }}.zip
